name: Test Trigger
on:
  push:
    branches: [development]
  workflow_dispatch:
jobs:
  test:
    runs-on: dev # Gunakan runner GitHub standar dulu untuk debug
    steps:
      - name: Say Hello
        run: echo "Hello from test trigger!"
